---
name: Build container and push to Dockerhub
on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push container to Dockerhub
        uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: zerobaseio/smart-tracing
          tag_with_ref: true
          tag_with_sha: true
