---
name: Build Dockerfile
on:
  pull_request:
    paths:
      - ./Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run local registry
        run: docker run -d -p 5000:5000 registry:2

      - name: Build and push image
        uses: docker/build-action@v1
        env:
          DOCKER_BUILDKIT: 1
        with:
          registry: localhost:5000
          repository: zerobaseio/smart-tracing
          tags: pull_request

      - name: Remove local image
        run: docker image rm localhost:5000/zerobaseio/smart-tracing:pull_request

      - name: Run image from registry
        run: docker run localhost:5000/zerobaseio/smart-tracing:pull_request
